version: '3'

services:
  api:
    restart: always
    build: ./api
    container_name: api
    ports:
      - 5555:5000
    depends_on:
      - mysql
  frontend:
    restart: always
    build: ./frontend
    container_name: frontend
    ports:
      - 8954:8954
  mysql:
    restart: always
    image: mysql
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=time_db
    volumes:
      - mysql_data:/var/lib/mysql
  adminer:
    restart: always
    image: adminer
    container_name: adminer
    ports:
      - 8914:8080

volumes:
  mysql_data:


